/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/iphone.gltf');

  useFrame(()=>{
    return group.current.rotation.z += 0.01;
  })

  return (
    <group ref={group} {...props} dispose={null} scale={20} rotation={[1.57,0,0]}>
      <mesh geometry={nodes.Body.geometry} material={materials['Material.001']}>
        <mesh geometry={nodes.Glass.geometry} material={materials.Material} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/iphone.gltf')
