/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Model({ props,data }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/laptokNEW.glb');
  useFrame(({ clock })=>{
    
    return group.current.rotation.y += 0.01;

  });
  return (
    // scale={data.width/3000}
  <group ref={group} {...props} dispose={null} scale={data.width/1500} position={[0,-1,-3.8]} rotation={[0.3,0,0]}> 
  <group position={[0, 0, -0.25]} scale={[5, 1.83, 4]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials.Klawa} />
        <mesh geometry={nodes.Plane_3.geometry} material={materials['default']} />
        <mesh geometry={nodes.Plane_4.geometry} material={materials['default.001']} />
        <mesh geometry={nodes.Plane_5.geometry} material={materials['default.002']} />
        <mesh geometry={nodes.Plane_6.geometry} material={materials['default.003']} />
        <mesh geometry={nodes.Plane_7.geometry} material={materials['default.004']} />
        <mesh geometry={nodes.Plane_8.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Plane_9.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/laptokNEW.glb')
