/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mobile.glb');

  useFrame(()=>{
    return group.current.rotation.y += 0.01;
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Phone.geometry} material={materials.body} position={[0, 1.01, 0]} scale={3}>
        <mesh geometry={nodes.Cam_module.geometry} material={materials.logo} position={[-0.27, 0.71, 0.07]} scale={1.19} />
        <mesh geometry={nodes.Circle.geometry} material={materials.logo} position={[0, 0.03, 0.07]} rotation={[Math.PI / 2, 0, 0]} scale={0.15} />
        <mesh geometry={nodes.flash.geometry} material={materials.flash} position={[-0.15, 0.85, 0.1]} scale={0.37} />
        <group position={[-0.35, 0.79, 0.09]} scale={1.47}>
          <mesh geometry={nodes.Cylinder.geometry} material={materials.logo} />
          <mesh geometry={nodes.Cylinder_1.geometry} material={materials['inner lens']} />
          <mesh geometry={nodes.Cylinder_2.geometry} material={materials['focal lens']} />
        </group>
        <group position={[-0.35, 0.62, 0.09]} scale={1.47}>
          <mesh geometry={nodes.Cylinder007.geometry} material={materials.logo} />
          <mesh geometry={nodes.Cylinder007_1.geometry} material={materials['inner lens']} />
          <mesh geometry={nodes.Cylinder007_2.geometry} material={materials['focal lens']} />
        </group>
        <group position={[-0.19, 0.71, 0.09]} scale={1.47}>
          <mesh geometry={nodes.Cylinder008.geometry} material={materials.logo} />
          <mesh geometry={nodes.Cylinder008_1.geometry} material={materials['inner lens']} />
          <mesh geometry={nodes.Cylinder008_2.geometry} material={materials['focal lens']} />
        </group>
        <mesh geometry={nodes.Power_switch.geometry} material={materials.body} position={[-0.53, 0.23, 0]} scale={[1, 1.99, 1]} />
        <mesh geometry={nodes.Screen.geometry} material={materials.screen} position={[0, 0, 0.02]} scale={0.97} />
        <mesh geometry={nodes.Volume_rocker.geometry} material={materials.body} position={[0.53, 0.43, 0]} scale={[1, 1.3, 1]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/mobile.glb')
