/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/laptop.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.Material} position={[0, 0, 1.06]} scale={[5, 1.83, 4]} />
      <group position={[0, 3.68, -4.5]} rotation={[1.17, 0, 0]} scale={[5, 1.83, 4]}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.Klawa} position={[-4.12, 0.17, -1.41]} scale={[0.24, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Klawa} position={[-3.39, 0.17, -1.41]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Klawa} position={[-2.77, 0.17, -1.41]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Klawa} position={[-1.55, 0.17, -1.41]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Klawa} position={[-2.16, 0.17, -1.41]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.Klawa} position={[0.28, 0.17, -1.41]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials.Klawa} position={[0.9, 0.17, -1.41]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.Klawa} position={[-0.33, 0.17, -1.41]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials.Klawa} position={[-0.94, 0.17, -1.41]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.Klawa} position={[2.75, 0.17, -1.41]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials.Klawa} position={[3.86, 0.17, -1.41]} scale={[0.67, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials.Klawa} position={[2.13, 0.17, -1.41]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials.Klawa} position={[1.52, 0.17, -1.41]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials.Klawa} position={[2.09, 0.17, -1.92]} scale={[0.26, 0.05, 0.17]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials.Klawa} position={[2.76, 0.17, -1.92]} scale={[0.26, 0.05, 0.17]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.Klawa} position={[3.45, 0.17, -1.92]} scale={[0.26, 0.05, 0.17]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials.Klawa} position={[-0.6, 0.17, -1.92]} scale={[0.26, 0.05, 0.17]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials.Klawa} position={[0.06, 0.17, -1.92]} scale={[0.26, 0.05, 0.17]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials.Klawa} position={[1.38, 0.17, -1.92]} scale={[0.26, 0.05, 0.17]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials.Klawa} position={[0.7, 0.17, -1.92]} scale={[0.26, 0.05, 0.17]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials.Klawa} position={[-2.02, 0.17, -1.92]} scale={[0.26, 0.05, 0.17]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials.Klawa} position={[-1.24, 0.17, -1.92]} scale={[0.26, 0.05, 0.17]} />
      <mesh geometry={nodes.Cube023.geometry} material={materials.Klawa} position={[-2.74, 0.17, -1.92]} scale={[0.26, 0.05, 0.17]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials.Klawa} position={[-3.41, 0.17, -1.92]} scale={[0.26, 0.05, 0.17]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials.Klawa} position={[-4.1, 0.17, -1.92]} scale={[0.26, 0.05, 0.17]} />
      <mesh geometry={nodes.Cube025.geometry} material={materials.Klawa} position={[4.26, 0.17, -1.92]} scale={[0.26, 0.05, 0.17]} />
      <mesh geometry={nodes.Cube026.geometry} material={materials.Klawa} position={[1.52, 0.17, -0.81]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials.Klawa} position={[2.13, 0.17, -0.81]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube028.geometry} material={materials.Klawa} position={[2.74, 0.17, -0.81]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube029.geometry} material={materials.Klawa} position={[-0.94, 0.17, -0.81]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube030.geometry} material={materials.Klawa} position={[-0.33, 0.17, -0.81]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube031.geometry} material={materials.Klawa} position={[0.89, 0.17, -0.81]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube032.geometry} material={materials.Klawa} position={[0.28, 0.17, -0.81]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials.Klawa} position={[-2.17, 0.17, -0.81]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube034.geometry} material={materials.Klawa} position={[-1.55, 0.17, -0.81]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube035.geometry} material={materials.Klawa} position={[-2.78, 0.17, -0.81]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube036.geometry} material={materials.Klawa} position={[-3.39, 0.17, -0.81]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube038.geometry} material={materials.Klawa} position={[4.11, 0.17, -0.8]} scale={[0.38, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube039.geometry} material={materials.Klawa} position={[-4.05, 0.17, -0.8]} scale={[0.31, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials.Klawa} position={[-3.77, 0.17, -0.21]} scale={[0.6, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube040.geometry} material={materials.Klawa} position={[3.89, 0.17, -0.21]} scale={[0.6, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube041.geometry} material={materials.Klawa} position={[-2.71, 0.17, -0.22]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube042.geometry} material={materials.Klawa} position={[-2.1, 0.17, -0.22]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube043.geometry} material={materials.Klawa} position={[-0.87, 0.17, -0.22]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube044.geometry} material={materials.Klawa} position={[-1.49, 0.17, -0.22]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube045.geometry} material={materials.Klawa} position={[0.96, 0.17, -0.22]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube046.geometry} material={materials.Klawa} position={[1.57, 0.17, -0.22]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube047.geometry} material={materials.Klawa} position={[0.35, 0.17, -0.22]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube048.geometry} material={materials.Klawa} position={[-0.26, 0.17, -0.22]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube050.geometry} material={materials.Klawa} position={[2.81, 0.17, -0.22]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube051.geometry} material={materials.Klawa} position={[2.2, 0.17, -0.22]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube049.geometry} material={materials.Klawa} position={[3.37, 0.17, -0.81]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube052.geometry} material={materials.Klawa} position={[1.93, 0.17, 0.39]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube053.geometry} material={materials.Klawa} position={[2.55, 0.17, 0.39]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube054.geometry} material={materials.Klawa} position={[-0.53, 0.17, 0.39]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube055.geometry} material={materials.Klawa} position={[0.08, 0.17, 0.39]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube056.geometry} material={materials.Klawa} position={[1.31, 0.17, 0.39]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube057.geometry} material={materials.Klawa} position={[0.7, 0.17, 0.39]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube058.geometry} material={materials.Klawa} position={[-1.75, 0.17, 0.39]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube059.geometry} material={materials.Klawa} position={[-1.14, 0.17, 0.39]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube060.geometry} material={materials.Klawa} position={[-2.36, 0.17, 0.39]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube062.geometry} material={materials.Klawa} position={[3.76, 0.17, 0.4]} scale={[0.75, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube063.geometry} material={materials.Klawa} position={[-3.62, 0.17, 0.4]} scale={[0.75, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube061.geometry} material={materials.Klawa} position={[-4.13, 0.17, 1.02]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube064.geometry} material={materials.Klawa} position={[-2.86, 0.17, 1.02]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube065.geometry} material={materials.Klawa} position={[-3.47, 0.17, 1.02]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube066.geometry} material={materials.Klawa} position={[-2.25, 0.17, 1.02]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube067.geometry} material={materials.Klawa} position={[-0.24, 0.17, 1.02]} scale={[1.67, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube068.geometry} material={nodes.Cube068.material} position={[0.7, 0.17, 0.39]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube069.geometry} material={nodes.Cube069.material} position={[1.31, 0.17, 0.39]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube070.geometry} material={nodes.Cube070.material} position={[0.08, 0.17, 0.39]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube071.geometry} material={nodes.Cube071.material} position={[-0.53, 0.17, 0.39]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube072.geometry} material={nodes.Cube072.material} position={[2.55, 0.17, 0.39]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube073.geometry} material={materials.Klawa} position={[1.93, 0.17, 0.39]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube074.geometry} material={materials.Klawa} position={[2.38, 0.17, 1.03]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube075.geometry} material={materials.Klawa} position={[2.99, 0.17, 1.03]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube076.geometry} material={materials.Klawa} position={[1.77, 0.17, 1.03]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube078.geometry} material={materials.Klawa} position={[4.23, 0.17, 1.03]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube079.geometry} material={materials.Klawa} position={[3.62, 0.17, 1.03]} scale={[0.25, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube077.geometry} material={materials['Material.004']} position={[-0.89, 0.14, 4.4]} scale={[0.8, 0.05, 0.25]} />
      <mesh geometry={nodes.Cube080.geometry} material={materials['Material.004']} position={[0.84, 0.14, 4.4]} scale={[0.8, 0.05, 0.25]} />
    </group>
  )
}

useGLTF.preload('/laptop.glb')
